spring:
  application:
    name: AUTHSERVICE

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8040/eureka/
instance:
  hostname: localhost

  server:
    port: 8044
